spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  cloud:
    gcp:
      storage:
        enabled: true
        credentials:
          location: src\main\resources\rock-partition-425300-s4-4bd76d361694.json
          scopes: https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/sqlservice.admin
        project-id: ${GCP_PROJECT_ID}
        bucket: ${GCP_BUCKET_NAME}
    servlet:
      multipart:
        enabled: true

oauth:
  provider:
    kakao:
      user-info-uri: https://kapi.kakao.com/v2/user/me
    naver:
      user-info-uri: https://openapi.naver.com/v1/nid/me
    google:
      user-info-uri: https://www.googleapis.com/userinfo/v2/me

jwt:
  access-token:
    expire-length: 3600000 # 1시간
  refresh-token:
    expire-length: 129600000 # 15일
  token:
    secret-key: ${TOKEN_SECRET_KEY}


