spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    url: # 설정 필요

oauth:
  provider:
    kakao:
      user-info-uri: https://kapi.kakao.com/v2/user/me
    naver:
      user-info-uri: https://openapi.naver.com/v1/nid/me
    google:
      user-info-uri: https://www.googleapis.com/userinfo/v2/me

jwt:
  access-token:
    expire-length: 3600000 # 1시간
  refresh-token:
    expire-length: 129600000 # 15일
  token:
    secret-key: ${{ secrets.TOKEN_SECRET_KEY}}

cloud:
    gcp:
      storage:
        enabled: true
        credentials:
          location: src\main\resources\rock-partition-425300-s4-4bd76d361694.json
          scopes: https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/sqlservice.admin
        project-id: rock-partition-425300-s4
        bucket: nbdream_bucket_1
    servlet:
      multipart:
        enabled: true
