spring:
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
    url: 
  cloud:
    gcp:
      storage:
        enabled: true
        credentials:
          location: src/main/resources/rock-partition-425300-s4-4bd76d361694.json
          scopes: https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/sqlservice.admin
        project-id: 
        bucket: 
    servlet:
      multipart:
        enabled: true


oauth:
  provider:
    kakao:
      user-info-uri: https://kapi.kakao.com/v2/user/me
    naver:
      user-info-uri: https://openapi.naver.com/v1/nid/me
    google:
      user-info-uri: https://www.googleapis.com/userinfo/v2/me

jwt:
  access-token:
    expire-length: 3600000 # 1시간
  refresh-token:
    expire-length: 129600000 # 15일
  token:
    secret-key: 
    
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

weather:
  service-key: 

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent
    key: 
soil:
  api:
    url: http://apis.data.go.kr/1390802/SoilEnviron/SoilExam/getSoilExam
    key: 
