name: Bug Template
description: Bug 사항이 있을 때 사용하는 템플릿
title: "[Bug]: "
labels: ["🐞 bug"]

body:
  - type: textarea
    id: what-bug
    attributes:
      label: Bug Report
      description: 어떤 버그인지 설명해주세요.
      placeholder: ex. 회원 가입 시에 이메일 중복 검사를 하지 않아 중복되는 이메일을 가지는 회원이 생성되는 버그
    validations:
      required: true

  - type: textarea
    id: bug-flow
    attributes:
      label: Bug Flow(Optional)
      description: 버그가 발생하게 된 Flow를 알려주세요.
      placeholder: ex. 입력받은 이메일의 중복 검사를 하지 않아 중복된 이메일이 생성되고, 이 이메일을 이용하는 쿼리는 에러가 발생한다.
    validations:
      required: true
     
  - type: input
    id: related-bug
    attributes:
      label: Related Bug(Optaional)
      description: 관련된 버그 이슈
      placeholder: "ex. #32, #23"
    validations:
      required: false
