name: Issue Feature 템플릿
description: 기능 추가할때 사용하는 템플릿
title: "[Feat]: "
labels: ["✨ feat"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업해야되는 Feature에 대한 설명을 적어주세요.
      placeholder: ex. JWT를 이용하여 인증/인가 기능을 구현한다.
    validations:
      required: true
  - type: input
    id: prepare-issue
    attributes:
      label: Prepare Issue(Optional)
      description: 관련된 Prepare가 있다면 적어주세요.
      placeholder: "ex. #14"
    validations:
      required: false
  - type: textarea
    id: related-view
    attributes:
      label: 참고(Optional)
      description: 참고 사항
      placeholder: ex. Access Token과 Refresh Token 탈취에 대한 대책을 마련해야 함.
    validations:
      required: false
