name: Java CICD with Gradle

on:
  push:
    branches: [ "cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create json
        run: |
          touch ./src/main/resources/rock-partition-425300-s4-4bd76d361694.json
          echo "${{ secrets.NB_STORAGE_KEY}}" > ./src/main/resources/rock-partition-425300-s4-4bd76d361694.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      - name: Copy jar file to remote VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          port: ${{ secrets.NB_SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "/home/nbdream/app"
          strip_components: 2
