name: Java CICD with Gradle

on:
  push:
    branches: [ "cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy jar file to remote VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          port: ${{ secrets.NB_SERVER_PORT }}
          source: "."
          target: "/home/nbdream/test"
          strip_components: 1

      - name: Build and Deploy on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          port: ${{ secrets.NB_SERVER_PORT }}
          script: |
            cd /home/nbdream/test
            ./gradlew clean build --exclude-task test
            sudo bash deploy-nbdream.sh
