name: Java CICD with Gradle

env:
  RESOURCE_PATH: /home/nbdream/app/src/main/resources/application.yml

on:
  push:
    branches: [ "cicd" ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set yml file 
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }} 
        env:
          weather.service-key: ${{secrets.WEATHER_API_KEY}}
          gemini.api.key: ${{secrets.GEMINI_API_KEY}}
          soil.api.key: ${{secrets.SOIL_ENVIRON_API_KEY}}
          jwt.token.secret-key: ${{secrets.TOKEN_SECRET_KEY}}
          spring.cloud.gcp.storage.project-id: ${{secrets.GCP_PROJECT_ID}}
          spring.cloud.gcp.storage.bucket: ${{secrets.GCP_BUCKET_NAME}}
          spring.datasource.username: ${{secrets.DB_USERNAME}}
          spring.datasource.password: ${{secrets.DB_PASSWORD}}
          spring.datasource.url: ${{secrets.DB_URL}}

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      - name: Copy jar file to remote VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          port: ${{ secrets.NB_SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "/home/nbdream/app"
          strip_components: 2

      - name: Deploy new version in VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          script: sudo bash /home/nbdream/app/deploy-nbdream.sh

