name: Java CICD with Gradle

on:
  push:
    branches: [ "dev" ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SOIL_ENVIRON_API_KEY: ${{ secrets.SOIL_ENVIRON_API_KEY }}

      - name: Copy jar file to remote VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          port: ${{ secrets.NB_SERVER_PORT }}
          source: "build/libs/*.jar"
          target: "/home/nbdream/app"
          strip_components: 2

      - name: Deploy new version in VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NB_SERVER_HOST }}
          key: ${{ secrets.NB_SERVER_SSH_KEY }}
          username: ${{ secrets.NB_SERVER_USER }}
          script: sudo bash /home/nbdream/app/deploy-nbdream.sh

